# Generated by Django 4.2.27 on 2025-12-23 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('show_time', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=100)),
                ('dataandtime', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.EmailField(max_length=254, unique=True)),
                ('orderid', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
                ('currecy', models.CharField(default='INR', max_length=50)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
